### ISSUE TITLE
Item descriptions not loading on some items.

### ISSUE THREAD

**Issue by Qupu** [Xanaxiel/ToS-Addons#5] opened 2016-05-16 01:05 UTC
Some item descriptions dont load at all after the newest update.
But somehow if its first item you look when you look at items in inventory it shows the description but not the addon parts like collections it belongs to, also you can go to other problem items too without problem (expect addon not working on them).

Items that have this problem in my inventory currently:
Hanaming Petal
Vikaras Core
Oak Wood
Pine Wood (and no its not all woods ash works fine)
Tipio Stamen
Glizardon Bones
Crystal Spider Feelers
Sauga Core
Boowook Core

These items are not working for me atleast and i have a lot of materials in my inventory

**Comment by Xanaxiel** [comment] 2016-05-16 07:43
Will close as duplicate of issue #6

**Closed as completed by Xanaxiel** 2016-05-16 07:43 UTC
